### ISSUE TITLE
高危事件报警

### ISSUE THREAD

**Issue by ellenzhu** [Green-m/Demo#2]
Hi,还有一个疑问，请帮忙解答下。
我现在就用的community.rules里面的规则，但是怎么筛选出报警事件呢？应该不需要每个severity=1的时候都报警吧。一般哪些sid需要报警呢

**Comment by Green-m** [comment]
这个要靠自己积累哦，我也只是添加了那个永恒之蓝的规则报警，其他的都没有添加。

**Comment by ellenzhu** [comment]
好哒
